### PR TITLE
Fix disappearing when clicking show desktop button.

### PR DESCRIPTION
**Pull request by Lucarnosky**
Fixed as suggested in the issues

### CODE REVIEW

**Comment by Twometer** [comment]
Thank you, that looks promising. Once I have some time I'll test it and release a new version

**Comment by Lucarnosky** [comment]
I've made some test by myself, it looks working on first instance, but there is 2 new unexpected behaviour:
 The first is that if you click again the button to restore all the windows,  it won't do it. 
Second is that after some time the no fence will hide when clicking the show desktop button, but if you will raise any of the open windows, it will restore.

In general works better than beginning

**Comment by Twometer** [comment]
Now, that's cool, I just tried it and it seems to work really well for me too. I also noticed that restoring the minimized windows stopped working, which is kind of annoying but worth it.

**Comment by Twometer** [comment]
Thanks for the contribution :)

**Comment by Lucarnosky** [comment]
Glad to contribute

**Pull request merged**
